#!/usr/bin/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

# shellcheck disable=SC2086
exec rar2fs "${SOURCE}" "${MOUNTPOINT}" -f --date-rar --seek-length=1 --no-inherit-perm -o auto_unmount -o allow_other ${ARGS}
