#!/usr/bin/with-contenv bash
# shellcheck shell=bash

exec rar2fs -f --date-rar --seek-length=1 -o auto_unmount -o allow_other -o uid="${PUID}" -o gid="${PGID}" -o umask="${UMASK}" "${INPUT_DIR}" "${OUTPUT_DIR}"
