name: Version check
on:
  schedule:
    - cron:  '15,45 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [stable]
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ matrix.branch }}
        token: ${{ secrets.PERSONAL_TOKEN }}
    - name: Update files
      run: |
        bash update.sh
      id: update_files
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_ACTOR: ${{ github.actor }}
    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v4.5.1
      with:
        commit_message: ${{ format('Updated to version - {0}', steps.update_files.outputs.version) }}
        branch: ${{ matrix.branch }}
