name: Upstream digests check
on:
  schedule:
    - cron:  '5 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [stable]
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ matrix.branch }}
        token: ${{ secrets.PERSONAL_TOKEN }}
    - name: Check for updated digests
      run: |
        bash update.sh checkdigests
    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v4.5.1
      with:
        commit_message: Upstream digests have changed
        branch: ${{ matrix.branch }}
