#!/usr/bin/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

echo "
----------------------------------------------------------------------
ENVIRONMENT
----------------------------------------------------------------------
PUID=${PUID}
PGID=${PGID}
UMASK=${UMASK}
TZ=${TZ}
SOURCE=${SOURCE}
MOUNTPOINT=${MOUNTPOINT}
----------------------------------------------------------------------
"

groupmod -o -g "${PGID}" hotio
usermod -o -u "${PUID}" hotio
